export const MATERIAL_TYPE_ENUM = {
  PROSP_EXPL_MINAS_PEDR: 'PROSP_EXPL_MINAS_PEDR',
  AGRIC_PROC_ALIM: 'AGRIC_PROC_ALIM',
  PROC_MAD_PAINEL_MOB_PAPEL: 'PROC_MAD_PAINEL_MOB_PAPEL',
  IND_COURO_TEXTIL: 'IND_COURO_TEXTIL',
  REF_PETR_PURIF_GASNAT_TRATCARV: 'REF_PETR_PURIF_GASNAT_TRATCARV',
  PROC_QUIM_INORG: 'PROC_QUIM_INORG',
  PROC_QUIM_ORG: 'PROC_QUIM_ORG',
  REVEST_COLA_VED: 'REVEST_COLA_VED',
  IND_FOTOGRAFICA: 'IND_FOTOGRAFICA',
  PROC_TERMICOS: 'PROC_TERMICOS',
  TRAT_QUIM_REV_METAIS: 'TRAT_QUIM_REV_METAIS',
  MOLD_TRAT_MET_PLAST: 'MOLD_TRAT_MET_PLAST',
  OLEOS_USAD_RESID_COMB_LIQ: 'OLEOS_USAD_RESID_COMB_LIQ',
  SOLV_FLUID_REFRIG_GAS_PROP_ORG: 'SOLV_FLUID_REFRIG_GAS_PROP_ORG',
  EMB_ABSORV_PANOS_MATFILTR_VESTPROT: 'EMB_ABSORV_PANOS_MATFILTR_VESTPROT',
  NAO_ESPEC: 'NAO_ESPEC',
  CONSTR_DEMOLIC: 'CONSTR_DEMOLIC',
  SERV_SAUDE: 'SERV_SAUDE',
  INST_GEST_RESID_EST_TRAT_AGUA: 'INST_GEST_RESID_EST_TRAT_AGUA',
  SOLID_URB_EQUIP: 'SOLID_URB_EQUIP',
  RESID_ELETR: 'RESID_ELETR'
};

export const MATERIAL_TYPE_LABEL = {
  PROSP_EXPL_MINAS_PEDR: 'Pedras, pedriscos, minério',
  AGRIC_PROC_ALIM: 'Produtos agrícolas ou alimentos',
  PROC_MAD_PAINEL_MOB_PAPEL:
    'Madeira, painéis, mobiliário e papel',
  IND_COURO_TEXTIL: 'Produtos de couro e têxtil',
  REF_PETR_PURIF_GASNAT_TRATCARV:
    'Produtos derivados de petróleo, gás natural e carvão',
  PROC_QUIM_INORG: 'Produtos químicos inorgânicos',
  PROC_QUIM_ORG: 'Produtos químicos orgânicos',
  REVEST_COLA_VED: 'Revestimentos (tintas, vernizes, colas vedantes)',
  IND_FOTOGRAFICA: 'Equipamentos fotográficos',
  PROC_TERMICOS: 'Resíduo oriundo de processos térmicos',
  TRAT_QUIM_REV_METAIS: 'Produtos químicos e revestimentos de metais',
  MOLD_TRAT_MET_PLAST:
    'Metais e plásticos',
  OLEOS_USAD_RESID_COMB_LIQ: 'Óleos e resíduos de combustíveis',
  SOLV_FLUID_REFRIG_GAS_PROP_ORG:
    'Solventes, fluídos de refrigeração e gases propulsores orgânicos',
  EMB_ABSORV_PANOS_MATFILTR_VESTPROT:
    'Embalagens, panos, vestuário de proteção',
  NAO_ESPEC: 'Não especificados',
  CONSTR_DEMOLIC: 'Produtos de construção e demolição',
  SERV_SAUDE: 'Produtos de saúde',
  INST_GEST_RESID_EST_TRAT_AGUA:
    'Instalações de gestão de resíduos, de estações de tratamento de águas residuais',
  SOLID_URB_EQUIP:
    'Sólidos urbanos e equipamentos (domésticos, comércio, indústria)',
  RESID_ELETR:
    'Resíduos eletrônicos'
};

export const MATERIAL_TYPE_LIST = [
  {
    value: MATERIAL_TYPE_LABEL.PROSP_EXPL_MINAS_PEDR,
    id: MATERIAL_TYPE_ENUM.PROSP_EXPL_MINAS_PEDR,
  },
  {
    value: MATERIAL_TYPE_LABEL.AGRIC_PROC_ALIM,
    id: MATERIAL_TYPE_ENUM.AGRIC_PROC_ALIM,
  },
  {
    value: MATERIAL_TYPE_LABEL.PROC_MAD_PAINEL_MOB_PAPEL,
    id: MATERIAL_TYPE_ENUM.PROC_MAD_PAINEL_MOB_PAPEL,
  },
  {
    value: MATERIAL_TYPE_LABEL.IND_COURO_TEXTIL,
    id: MATERIAL_TYPE_ENUM.IND_COURO_TEXTIL,
  },
  {
    value: MATERIAL_TYPE_LABEL.REF_PETR_PURIF_GASNAT_TRATCARV,
    id: MATERIAL_TYPE_ENUM.REF_PETR_PURIF_GASNAT_TRATCARV,
  },
  {
    value: MATERIAL_TYPE_LABEL.PROC_QUIM_INORG,
    id: MATERIAL_TYPE_ENUM.PROC_QUIM_INORG,
  },
  {
    value: MATERIAL_TYPE_LABEL.PROC_QUIM_ORG,
    id: MATERIAL_TYPE_ENUM.PROC_QUIM_ORG,
  },
  {
    value: MATERIAL_TYPE_LABEL.REVEST_COLA_VED,
    id: MATERIAL_TYPE_ENUM.REVEST_COLA_VED,
  },
  {
    value: MATERIAL_TYPE_LABEL.IND_FOTOGRAFICA,
    id: MATERIAL_TYPE_ENUM.IND_FOTOGRAFICA,
  },
  {
    value: MATERIAL_TYPE_LABEL.PROC_TERMICOS,
    id: MATERIAL_TYPE_ENUM.PROC_TERMICOS,
  },
  {
    value: MATERIAL_TYPE_LABEL.TRAT_QUIM_REV_METAIS,
    id: MATERIAL_TYPE_ENUM.TRAT_QUIM_REV_METAIS,
  },
  {
    value: MATERIAL_TYPE_LABEL.MOLD_TRAT_MET_PLAST,
    id: MATERIAL_TYPE_ENUM.MOLD_TRAT_MET_PLAST,
  },
  {
    value: MATERIAL_TYPE_LABEL.OLEOS_USAD_RESID_COMB_LIQ,
    id: MATERIAL_TYPE_ENUM.OLEOS_USAD_RESID_COMB_LIQ,
  },
  {
    value: MATERIAL_TYPE_LABEL.SOLV_FLUID_REFRIG_GAS_PROP_ORG,
    id: MATERIAL_TYPE_ENUM.SOLV_FLUID_REFRIG_GAS_PROP_ORG,
  },
  {
    value: MATERIAL_TYPE_LABEL.EMB_ABSORV_PANOS_MATFILTR_VESTPROT,
    id: MATERIAL_TYPE_ENUM.EMB_ABSORV_PANOS_MATFILTR_VESTPROT,
  },
  {
    value: MATERIAL_TYPE_LABEL.CONSTR_DEMOLIC,
    id: MATERIAL_TYPE_ENUM.CONSTR_DEMOLIC,
  },
  {
    value: MATERIAL_TYPE_LABEL.SERV_SAUDE,
    id: MATERIAL_TYPE_ENUM.SERV_SAUDE,
  },
  {
    value: MATERIAL_TYPE_LABEL.INST_GEST_RESID_EST_TRAT_AGUA,
    id: MATERIAL_TYPE_ENUM.INST_GEST_RESID_EST_TRAT_AGUA,
  },
  {
    value: MATERIAL_TYPE_LABEL.SOLID_URB_EQUIP,
    id: MATERIAL_TYPE_ENUM.SOLID_URB_EQUIP,
  },
  {
    value: MATERIAL_TYPE_LABEL.NAO_ESPEC,
    id: MATERIAL_TYPE_ENUM.NAO_ESPEC,
  },
  {
    value: MATERIAL_TYPE_LABEL.RESID_ELETR,
    id: MATERIAL_TYPE_ENUM.RESID_ELETR,
  },
];
